# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vbguest.auto_update = true

  # create Amazon Web Services Management (osmgmt) node
  config.vm.define :osmgmt do |osmgmt_config|
    osmgmt_config.vm.box = "ubuntu/bionic64"
    osmgmt_config.vm.hostname = "osmgmt"
    osmgmt_config.vm.network :private_network, ip: "192.168.56.10"
    if Vagrant::Util::Platform.windows? then
    # Configuration SPECIFIC for Windows 10 hosts
      osmgmt_config.vm.synced_folder "aws-tenant/", "/home/vagrant/aws-tenant",
        id: "vagrant-root", owner: "vagrant", group: "vagrant",
        mount_options: ["dmode=0755,fmode=0774"]
      else
        osmgmt_config.vm.synced_folder "aws-tenant/", "/home/vagrant/aws-tenant",
        mount_options: ["dmode=755"]
    end
    osmgmt_config.vm.provider "virtualbox" do |vb|
      vb.name = "osmgmt"
      opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize opts
      vb.memory = "1024"
    end
    osmgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

end
