access_key          = "AWS ACCESS KEY ID"
secret_key          = "AWS SECRET ACCESS KEY"
token               = "AWS SESSION TOKEN"
region              = "us-east-1"
ssh_key_public      = "/home/vagrant/.ssh/id_rsa.pub"
ssh_key_private     = "/home/vagrant/.ssh/id_rsa"
