access_key          = "ASIAR4VNCOA2ZJQ6FNZO"
secret_key          = "ZmIPCYwlKeHdrQ81nLiK8mBTZwjCtfxRDHAZC51N"
token               = "FwoGZXIvYXdzEFUaDDbjMBVC5aS1aYzyYyLSAWsVJqywHMYb8h8KfY2UMrNn7mtzXz68pnp1vK2/PUFdOCjiuTrTYvxnDdIS1knoyX/ES16ixGxZsmR8EuYlirqGIO3t/px1tHLtjXkXIjNPRXsTrVNYbWHzSLclLABDRQkgonDaLuk9oiFyx4xLrz9iYiYa05aleCEs9liJitCFA7a9ICdPChrAKC0Vze0TtEdt3ZCw072C+auSbzwTr85PL44pV4GYlg3aKYqY1BRhhE1bIOczBDQQR2vjuhCyDDhFd90HgFEpwdIh9bqcArWemCjn1Z7wBTIt4Qu39rPo10rmBG5rrh5Z+h8TjY7qSDqpkqwrFRWwKAmoYkwDZlFBwFxu1MwD"
region              = "us-east-1"
ssh_key_public      = "/home/vagrant/.ssh/id_rsa.pub"
ssh_key_private     = "/home/vagrant/.ssh/id_rsa"
