access_key          = "ACCESS KEY"
secret_key          = "SECRET KEY"
token               = "TOKEN KEY"
region              = "us-east-1"
ssh_key_public      = "/home/vagrant/.ssh/id_rsa.pub"
ssh_key_private     = "/home/vagrant/.ssh/id_rsa"
